<?php
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event view template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_event = $this->getCurrentEvent();?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title event-title">
    <h1><?php echo $_event->getCaption(); ?></h1>
</div>
<div class="event-view">
    <div class="event-image">
            <?php if ($_event->getImage()) :?>
        <a href="<?php echo Mage::helper('istans_nailgallery/event')->getFileBaseUrl().$_event->getImage();?>">
            <span><?php echo basename($_event->getImage())?></span>
        </a>
    <?php endif;?>

    </div>
    <div class="event-caption">
        <?php echo Mage::helper('istans_nailgallery')->__('Caption');?>:<?php echo $_event->getCaption();?>

    </div>

</div>
