<?php
/** @var $this Itdelight_QuickOrder_Block_Quickorder */
?>
<div id="popup-quickorder" class="root-block-quickorder container">
    <div class="popup-quickorder">
        <span class="close-popup"></span>
        <div class="col-sm-6 q-left">
            <span class="head1"><?php echo $this->__("Ordering"); ?></span>
            <span><?php echo $this->__("Fill the form"); ?></span>
            <form name="quickorder" id="quickorder" method="post"
                  action="<?php echo Mage::getBaseUrl() . "popuporder/index/place_order"; ?>">
                <div class="select-wrapper">
                    <select name="payment" class="required-entry">
                        <option value="checkmo"><?php echo $this->__("in cash"); ?></option>
                        <option value="liqpay"><?php echo $this->__("cashless payments"); ?></option>
                        <option value="cashondelivery"><?php echo $this->__("cash on delivery"); ?></option>
                    </select>
                </div>
                <input name="first_name" type="text" placeholder="<?php echo $this->__("First Name"); ?>"
                       class="required-entry"/>
                <input name="last_name" type="text" placeholder="<?php echo $this->__("Last Name"); ?>"
                       class="required-entry"/>
                <div class="select-wrapper">
                    <select name="destination" id="quickorder-destination-switch" class="required-entry">
                        <option value="warehouse"><?php echo $this->__("To the warehouse"); ?></option>
                        <option value="address"><?php echo $this->__("To the address"); ?></option>
                    </select>
                </div>
                <!-- configurator -->
                <div class="select-wrapper">
                    <select name="city" id="warehouse-city" class="required-entry">
                        <option value=""><?php echo $this->__("Please choise the city"); ?></option>
                        <?php foreach (Mage::helper('sy_novaposhta')->getCities(true) as $city): ?>
                            <option value="<?php echo $city['Ref']; ?>">
                                <?php echo $city['DescriptionRu']; ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <!-- warehouse -->
                <div id="warehouse-form" style="display: block">
                    <div class="select-wrapper">
                        <select id="warehouse-storage" name="warehouse">
                            <option value=""><?php echo $this->__("Please choise the warehouse"); ?></option>
                        </select>
                    </div>
                </div>
                <!-- warehouse END -->
                <!-- address -->
                <div id="address-form" style="display: none">
                    <input name="street" type="text" placeholder="<?php echo $this->__("Street"); ?>"/>
                    <input name="house" type="text" placeholder="<?php echo $this->__("House"); ?>"/>
                    <input name="apartment" class="no-required" type="text" placeholder="<?php echo $this->__("Flat"); ?>"/>
                </div>
                <!-- address END -->
                <input id="email-qo" class="no-required" name="email" type="text"
                       placeholder="<?php echo $this->__("Email"); ?>"/>
                <input class="required-entry" name="tel" type="tel"
                       placeholder="<?php echo $this->__("Telephone"); ?>"/>
                <label id="show-comment" class="show-comment"
                       for="comment"><?php echo $this->__("Leave comment"); ?></label>
                <textarea id="comment" class="comment" rows="4" cols="45" name="comment"></textarea>
                <div class="input-wrapper">
                    <input type="checkbox" id="privacy-policy" checked="checked" />
                    <label class="check-policy" for="privacy-policy">
                        <?php echo $this->__("I agree "); ?><a
                            href="<?php echo Mage::getBaseUrl() . 'privacy-policy'; ?>"><?php echo $this->__("with the Privacy Policy"); ?></a>
                    </label>
                </div>
                <input type="hidden" name="price-data" id="price-data"/>

                <div class="quickorder__actions">
                    <button id="sendquickorder" class="btn-submit" type="submit"
                            value="Submit"><?php echo $this->__("Checkout"); ?></button>
                    <span class="continue-shopping-btn"><?php echo $this->__("Continue shopping"); ?></span>
                </div>
            </form>
        </div>
        <div class="col-sm-6 q-right">
            <script type="text/javascript">
                function removeItem(item) {
                    if (confirm('<?php echo $this->__('Are you sure you would like to remove this item from the shopping cart?'); ?>')) {
                        window.open(jQuery(item).data('link'), "_self");
                    }
                }

                function changePricePopup() {
                    var totalPrice = 0;
                    var dataprice = [];
                    jQuery(".item-qty-addon").each(function () {
                        var val = jQuery(this).val();
                        var count = jQuery(this).attr('data-price');
                        var name = jQuery(this).attr('name');
                        var string = [name, val];
                        dataprice.push(string);
                        totalPrice += (val * count);
                    });
                    jQuery("#price-data").val(JSON.stringify(dataprice));
                    jQuery("#popup-quickorder .subtotal .price").text(totalPrice + ',00 грн');
                }

                function addOneTo(item) {
                    var val = jQuery(item).val();
                    val++;
                    jQuery(item).val(val);
                    changePricePopup();
                }

                function remOneTo(item) {
                    var val = jQuery(item).val();
                    if (val > 1) {
                        val--;
                    }
                    jQuery(item).val(val);
                    changePricePopup();
                }
            </script>
            <!--            alobencher/default/template/magiccart/magicshop/checkout/cart/mini_cart.phtml-->
            <?php echo $this->getChildHtml('ajaxcart'); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function () {
        jQuery('.filter-link').click(function () {
            window.open(jQuery(this).data('link'), "_self");
            return false;
        });
        jQuery(".show-popup-quick-order").click(function () {
            jQuery("#popup-quickorder").fadeIn(200);
            jQuery('body').toggleClass('popup-shown');
            return false;
        });
        jQuery(".root-block-quickorder").click(function () {
            jQuery("#popup-quickorder").fadeOut(200);
            jQuery('body').removeClass('popup-shown');
            return false;
        });
        jQuery('.close-popup, .continue-shopping-btn').on('click', function () {
            jQuery('.root-block-quickorder').trigger('click');
        });
        jQuery(".popup-quickorder ").click(function (event) {
            event.stopPropagation();
        });
        jQuery("#privacy-policy").click(function () {
            jQuery(".check-policy ").click();
        });
        jQuery(".check-policy ").click(function () {
            if (jQuery("#privacy-policy").is(':checked')) {
                jQuery("#privacy-policy").prop('checked', false);
            } else {
                jQuery("#privacy-policy").prop('checked', true);
            }
        });
        jQuery("#show-comment").click(function () {
            if (jQuery("#comment").hasClass("show")) {
                jQuery("#comment").hide();
                jQuery("#comment").removeClass("show")
            } else {
                jQuery("#comment").show();
                jQuery("#comment").addClass("show")
            }
        });
        jQuery("#quickorder-destination-switch").on('change', function () {
            var select_val = jQuery("#quickorder-destination-switch").val();
            var warehouse_form = jQuery("#warehouse-form");
            var address_form = jQuery("#address-form");
            if (select_val == 'warehouse') {
                warehouse_form.show();
                address_form.hide();
            } else if (select_val == 'address') {
                warehouse_form.hide();
                address_form.show();
            }
        });
        jQuery("#warehouse-city").on('change', function () {
            if (jQuery("#quickorder-destination-switch").val() == "warehouse") {
                jQuery.ajax({
                    url: '<?php echo Mage::getBaseUrl()."popuporder/index/warehouse_city"; ?>',
                    data: jQuery("#warehouse-city").val(),
                    beforeSend: function () {
                        jQuery("#warehouse-storage").text('<option></option>');
                    },
                    success: function (data) {
                        var w_cities = JSON.parse(data);
                        jQuery.each(w_cities, function (index, value) {
                            var options = '<option value=' + value['Ref'] + '>' + value['DescriptionRu'] + '</option>';
                            jQuery("#warehouse-storage").append(options);
                        });
                    }
                })
            }
        });
        jQuery("#sendquickorder").click(function () {
            var check = true;
            jQuery("#quickorder .validation-failed").each(function () {
                jQuery(this).removeClass('validation-failed');
            });
            jQuery("#quickorder .required-entry").each(function () {
                if (this.value == "") {
                    jQuery(this).addClass('validation-failed');
                    check = false;
                }
            });
            if (jQuery("#quickorder-destination-switch").val() == "warehouse") {
                jQuery("#warehouse-storage").removeClass('validation-failed');
                if (jQuery("#warehouse-storage").val() == "") {
                    jQuery("#warehouse-storage").addClass('validation-failed');
                    check = false;
                }
            } else if (jQuery("#quickorder-destination-switch").val() == "address") {
                jQuery("#address-form input").each(function () {
                    jQuery(this).removeClass('validation-failed');
                });
                jQuery("#address-form input:not([name=apartment])").each(function () {
                    if (this.value == "") {
                        jQuery(this).addClass('validation-failed');
                        check = false;
                    }
                });
            }

            var pattern = /^([a-z0-9_\.-])+@[a-z0-9-]+\.([a-z]{2,4}\.)?[a-z]{2,4}$/i;

            if ( jQuery("#email-qo").val().length > 0 && !pattern.test(jQuery("#email-qo").val())) {
                jQuery("#email-qo").addClass('validation-failed');
                check = false;
            }

            if (jQuery("#privacy-policy").is(':checked')) {
                jQuery(".check-policy").removeClass('validation-failed');
            } else {
                check = false;
                jQuery(".check-policy").addClass('validation-failed');
            }

            if (check) {
                var city = jQuery("<input>")
                    .attr("type", "hidden")
                    .attr("name", "city").val(jQuery("select#warehouse-city option:checked").text());

                var warehouse = jQuery("<input>")
                    .attr("type", "hidden")
                    .attr("name", "warehouse").val(jQuery("select#warehouse-storage option:checked").text());

                jQuery("#quickorder").append(jQuery(city));
                jQuery("#quickorder").append(jQuery(warehouse));
                jQuery("#quickorder").submit();
            } else {
                return false;
            }
        });

        jQuery('#warehouse-city').select2();
    });
</script>
