<?php
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event image view widget template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_eventimage = $this->getCurrentEventimage();?>
<?php if ($_eventimage) :?>
    <div class="eventimage-widget-view">
        <h3><?php echo $_eventimage->getTitle()?></h3>
        <div>
            <div class="title-widget">
                <?php echo Mage::helper('istans_nailgallery')->__('Title');?>:<?php echo $_eventimage->getTitle();?>
            </div>
            <div class="file-widget">
                <?php echo Mage::helper('istans_nailgallery')->__('File');?>:<?php echo $_eventimage->getFile();?>
            </div>

        </div>
    </div>
<?php endif;?>
