<?php 
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Gallery list template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_gallerys = $this->getGallerys(); ?>
<div class="page-title gallery-title">
    <?php if (Mage::helper('istans_nailgallery/gallery')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('istans_nailgallery/gallery')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('istans_nailgallery')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('istans_nailgallery')->__('Gallery') ?></h1>
</div>
<?php if ($_gallerys->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="gallery-list-container">
    <?php foreach ($_gallerys as $_gallery) : ?>
        <div class="row">

        <div class="gallery-list-item">
            <a href="<?php echo $_gallery->getGalleryUrl()?>">
                <?php echo $_gallery->getCaption();?>
            </a><br />
        </div>

        </div>
    <?php endforeach;?>
    </>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('istans_nailgallery')->__('There are no gallery at this moment');?>
<?php endif;?>
