<?php $post = $this->getPost(); ?>
<?php
$_hpImages = Mage::helper('blog/images');
$width  = 870;
$height = 430;
?>
<div id="messages_product_view"><?php //echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="postWrapper post-detail">
    <div class="postTitle">
        <h1 class="name"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h1>
    </div>
    <div class="by post-date">
		<div class="number"><span><?php echo $post->getCreatedTime(); ?></span></div>
	</div>
	<!--<div class="tags"><?php //echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>-->
		<?php echo $this->getBookmarkHtml($post) ?>
    <?php /* output image */ ?>
    <div class="post-img">
        <?php echo $post->getImage() ? '<img  class="img-responsive" src="'. $_hpImages->resizeImg(basename($post->getImage()), $width, $height) .'" alt="blog" >' : ''; ?>
    </div>
    <?php /* end output image */ ?>
    <div class="postContent postContent-detail"><?php echo $post->getPostContent(); ?></div>
    <div class="link-social"><span><?php echo Mage::helper('itdelight_seoremarks')->__('Share')?></span>
        <ul class="link-list">
            <li class="link-icon">
						<span class="fa fa-facebook"
                              onclick='inWin("https://www.facebook.com/sharer/sharer.php?u=<?php echo $post->getAddress(); ?>")'
                              title="facebook">
							<span class="hidden">hidden</span>
						</span>
            </li>
            <li class="link-icon">
						<span class="fa fa-twitter"
                              onclick='inWin("https://twitter.com/share?url=<?php echo $post->getAddress(); ?>&text=<?php echo $post->getTitle(); ?>")'
                              title="instagram"><span class="hidden">hidden</span>
						</span>
            </li>
            <li class="link-icon">
						<span class="fa fa-google"
                              onclick='inWin("https://plus.google.com/share?url=<?php echo $post->getAddress(); ?>")'
                              title="google"><span class="hidden">hidden</span>
						</span>
            </li>
            <li class="link-icon">
						<span class="fa fa-pinterest"
                              onclick='inWin("http://pinterest.com/pin/create/button/?url=<?php echo $post->getAddress(); ?>&media=<?php echo $post->getImage(); ?>&description=<?php echo $post->getTitle(); ?>")'
                              title="pinterest"><span class="hidden">hidden</span>
						</span>
            </li>
        </ul>
    </div>
</div>

<!-- Comment Section -->

<script type="text/javascript">
    function inWin(a){
        if (a.href) a=a.href;
        window.open(a ,"_self");
        return false;
    }
</script>

<?php if ($this->getCommentsEnabled()): ?>
    <?php $comments = $this->getComment(); ?>
    <div class="postTitle"><a name="commentBox" ></a>
        <span><?php echo Mage::helper('itdelight_seoremarks')->__('Post Comments') ?></span>
    </div>
    <div class="blog-toolbar blog-toolbar-top">
        <?php //echo $this->getChildHtml('blog_comments_toolbar'); ?>
	</div>
        <?php foreach ($comments as $comment) : ?>
            <div class="commentWrapper">
                <div class="commentDetails"><h4 class="username"><?php echo $comment->getUser(); ?></h4> <?php echo $this->__("posted on") ?> <?php echo $this->formatDate($comment->getCreatedTime(), Mage::getStoreConfig('blog/blog/dateformat'), true); ?></div>
                <div class="commentContent"><?php echo nl2br($comment->getComment()); ?></div>
            </div>
        <?php endforeach; ?>
    <div class="blog-toolbar blog-toolbar-bottom">
		<?php //echo $this->getChildHtml('blog_comments_toolbar'); ?>
	</div>


    <?php if ($post->getComments()): ?>
        <div class="postError"><?php echo Mage::helper('blog')->__('Comments are Closed for this post') ?></div>
    <?php else: ?>
        <?php if ($this->getLoginRequired()): ?>
            <?php if ($this->helper('customer')->isLoggedIn()): ?>
                <form action="#" id="postComment" method="post">
                    <fieldset class="group-select">
                        <h4 class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></h4>
                        <ul class="form-list">
                            <li>

                                <div class="input-box aw-blog-comment-area">
                                    <label for="comment" class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                    <textarea name="comment" id="comment" title="<?php echo $this->__('Comment') ?>" class="required-entry input-text" style="height:150px;width:95%;" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                                </div>
                            </li>
                        </ul>
                    </fieldset>
                    <div class="button-set" style="width:96%">
                        <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                        <input name="email" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserEmail()) ?>"/>
                        <input name="user" type="hidden" value="<?php echo $this->htmlEscape($this->helper('blog')->getUserName()) ?>"/>
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <button class="form-button button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
                    </div>
                </form>

                <script type="text/javascript">
                    var contactForm = new VarienForm('postComment', false);
                </script>

            <?php else: ?>
                <p><?php echo Mage::helper('blog')->__('You must be logged in to post a comment.'); ?></p>
                <p><a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('blog')->__('click here'); ?></a> <?php echo Mage::helper('blog')->__('to log in'); ?></p>
            <?php endif ?>

        <?php else: ?>

            <form action="#" class="blog-postbox" id="postComment" method="post">
                <fieldset class="group-select">
				    <div class="post-title">
						<span class="legend"><?php echo Mage::helper('blog')->__('Submit Comment') ?></span>
					</div>
                    <ul class="form-list">
                        <li>
                            <div class="input-box">
                                <label class="required"><?php echo Mage::helper('blog')->__('Name') ?><em>*</em></label><br />
                                <input name="user" id="user" value="<?php echo $this->getCommentName(); ?>" title="<?php echo $this->__('Name') ?>" class="required-entry input-text" type="text" />
                            </div>

                            <div class="input-box">
                                <label  class="required"><?php echo Mage::helper('blog')->__('Email') ?><em>*</em></label><br />
                                <input name="email" id="email" value="<?php echo $this->getCommentEmail(); ?>" title="<?php echo $this->__('Email') ?>" class="required-entry input-text validate-email" type="text" />
                            </div>

                            <div class="clear"></div>

                            <div class="input-box aw-blog-comment-area">
                                <label class="required"><?php echo Mage::helper('blog')->__('Comment') ?><em>*</em></label><br />
                                <textarea name="comment" id="comment" title="<?php echo Mage::helper('blog')->__('Comment') ?>" class="required-entry input-text" cols="50" rows="5"><?php echo $this->getCommentText(); ?></textarea>
                            </div>
                        </li>

                        <?php
                        if (Mage::getStoreConfig('blog/recaptcha/enabled') && !$this->helper('customer')->isLoggedIn()) {
                            ?><li><?php
                require_once 'recaptcha/recaptchalib-aw.php';

                // Get a key from http://recaptcha.net/api/getkey
                $publickey = Mage::getStoreConfig('blog/recaptcha/publickey');
                $privatekey = Mage::getStoreConfig('blog/recaptcha/privatekey');
                $error = null;

                echo recaptcha_get_html($publickey, $error);
                            ?></li><?php
            }
                        ?>
                    </ul>
                </fieldset>
                <div class="button-set">
                    <input name="post_id" type="hidden" value="<?php echo $post->getPostId(); ?>" />
                    <button class="button form-button" type="submit"><span><span><?php echo Mage::helper('blog')->__('Submit Comment') ?></span></span></button>
					<p class="required"><?php echo $this->__('* Required Fields') ?></p>
                </div>
            </form>

            <script type="text/javascript">
                var contactForm = new VarienForm('postComment', false);
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    function inWin(a){
        if (a.href) a=a.href;
        window.open(a ,"_self");
        return false;
    }
</script>