<?php 
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Video list template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_videos = $this->getVideos(); ?>
<div class="page-title video-title">
    <?php if (Mage::helper('istans_nailgallery/video')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('istans_nailgallery/video')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('istans_nailgallery')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('istans_nailgallery')->__('Video') ?></h1>
</div>
<?php if ($_videos->getSize() > 0) :?>
    <?php echo $this->getPagerHtml(); ?>
    <div class="video-list-container">
    <?php foreach ($_videos as $_video) : ?>
        <div class="video-list-item">
            <a href="<?php echo $_video->getVideoUrl()?>">
                <?php echo $_video->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
    </div>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('istans_nailgallery')->__('There are no video at this moment');?>
<?php endif;?>
