<?php 
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event Event image list template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_eventimages = $this->getEventimages(); ?>
<?php if ($_eventimages->getSize() > 0) :?>
<div class="eventimage-title">
    <h2><?php echo Mage::helper('istans_nailgallery')->__('Event image') ?></h2>
</div>
<div class="eventimages-list-container">
    <?php foreach ($_eventimages as $_eventimage) : ?>
        <div class="eventimage-list-item">
            <a href="<?php echo $_eventimage->getEventimageUrl()?>">
                <?php echo $_eventimage->getTitle();?>
            </a><br />
        </div>
    <?php endforeach;?>
</div>
<?php endif;?>
