<script>
    jQuery(document).ready(function() {
        jQuery('#first-methods-payments-przelewy24').html('<?php echo $this->__("Payment methods visible on the first view:"); ?>');
        jQuery('#more-payments-text').html('<?php echo $this->__("Payment methods visible after click the button (more...):"); ?>');
		jQuery('.merchantIdLabel').html('<?php echo $this->__("Merchant ID:"); ?>');
		jQuery('.shopIdLabel').html('<?php echo $this->__("Shop ID:"); ?>');
		jQuery('.crcKeyLabel').html('<?php echo $this->__("CRC key:"); ?>');
		jQuery('.apiKeyLabel').html('<?php echo $this->__("API key"); ?>');
    });
</script>