<?php
/**
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE_AFL.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/afl-3.0.php
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2011-2012 Sergey Storchay <r8@r8.com.ua>
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<?php
    $personalDataAdmin = Mage::getStoreConfig('smartbees_modules_options/smartbees_customerattr/personal_data_administrator_checkout');
?>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <div class="buttons-set">
        <ul class="form-list">
            <li>
                <fieldset>
                    <ul>
                        <li class="wide">
                            <label for="ordercomment-comment"><?php echo Mage::helper('ordercomment')->__('Order Comment') ?></label>
                            <div class="input-box">
                                <textarea id="ordercomment-comment" class="input-text validation-passed" name="ordercomment[comment]" title="<?php echo $this->__('Order Comment') ?>" rows="5" cols="10"></textarea>
                            </div>
                        </li>
                    </ul>
                </fieldset>
            </li>
        </ul>
    </div>

    <?php if ((!Mage::getSingleton('customer/session')->isLoggedIn())): ?>
    <div class = "terms-and-personal-data" style="padding: 5px 30px; border-right: 1px solid #d9dde3; border-left: 1px solid #d9dde3;">
        <?php
            $storeCode = Mage::app()->getStore()->getCode();
            $websiteUrl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
        ?>
        <label for="agreement-label">
        <input type="checkbox" id="agreement-checkbox" name="agreement[checkbox]" value="1" class="required-entry" />
        <?php echo $this->__('*I have read and agreed to the ') ?><a href="<?php if($storeCode == "eu") echo $websiteUrl.'terms_eu'; else echo $websiteUrl.'terms_pl'; ?>" target="blank"><?php echo $this->__('Terms & conditions'); ?></a> i <a href="<?php if($storeCode == "eu") echo $websiteUrl.'privacy-policy'; else echo $websiteUrl.'polityka'; ?>" target="blank"><?php echo $this->__('Privacy Policy'); ?></a> 
        </label>

        <div class = "personal-data-admin">
            <?php echo $personalDataAdmin ?>
        </div>
    </div>
    <?php endif; ?>
</form>