<div id="canvas">
    <div class="zoom-icon zoom-icon-in"></div>
    <div class="magazine-viewport">
        <div class="container">
            <div class="magazine">
                <!-- Next button -->
                <div ignore="1" class="next-button"></div>
                <!-- Previous button -->
                <div ignore="1" class="previous-button"></div>
            </div>
        </div>
    </div>
    <!-- Thumbnails -->
    <div class="thumbnails">
        <div>
            <ul>
                <li class="i">
                    <img class="page-1" height="60" src="../media/catalogue/1-thumb.jpg" width="60" />
                    <span>1</span>
                </li>
                <li class="d">
                    <img class="page-2" height="60" src="../media/catalogue/2-thumb.jpg" width="60" />
                    <img class="page-3" height="60" src="../media/catalogue/3-thumb.jpg" width="60" />
                    <span>2-3</span>
                </li>
                <li class="d">
                    <img class="page-4" height="60" src="../media/catalogue/4-thumb.jpg" width="60" />
                    <img class="page-5" height="60" src="../media/catalogue/5-thumb.jpg" width="60" />
                    <span>4-5</span>
                </li>
                <li class="d">
                    <img class="page-6" height="60" src="../media/catalogue/6-thumb.jpg" width="60" />
                    <img class="page-7" height="60" src="../media/catalogue/7-thumb.jpg" width="60" />
                    <span>6-7</span>
                </li>
                <li class="d">
                    <img class="page-8" height="60" src="../media/catalogue/8-thumb.jpg" width="60" />
                    <img class="page-9" height="60" src="../media/catalogue/9-thumb.jpg" width="60" />
                    <span>8-9</span>
                </li>
                <li class="d">
                    <img class="page-10" height="60" src="../media/catalogue/10-thumb.jpg" width="60" />
                    <img class="page-11" height="60" src="../media/catalogue/11-thumb.jpg" width="60" />
                    <span>10-11</span>
                </li>
                <li class="d">
                    <img class="page-12" height="60" src="../media/catalogue/12-thumb.jpg" width="60" />
                    <img class="page-13" height="60" src="../media/catalogue/13-thumb.jpg" width="60" />
                    <span>12-13</span>
                </li>
                <li class="d">
                    <img class="page-14" height="60" src="../media/catalogue/14-thumb.jpg" width="60" />
                    <img class="page-15" height="60" src="../media/catalogue/15-thumb.jpg" width="60" />
                    <span>14-15</span>
                </li>
                <li class="d">
                    <img class="page-16" height="60" src="../media/catalogue/16-thumb.jpg" width="60" />
                    <img class="page-17" height="60" src="../media/catalogue/17-thumb.jpg" width="60" />
                    <span>16-17</span>
                </li>
                <li class="d">
                    <img class="page-18" height="60" src="../media/catalogue/18-thumb.jpg" width="60" />
                    <img class="page-19" height="60" src="../media/catalogue/19-thumb.jpg" width="60" />
                    <span>18-19</span>
                </li>
                <li class="d">
                    <img class="page-20" height="60" src="../media/catalogue/20-thumb.jpg" width="60" />
                    <img class="page-21" height="60" src="../media/catalogue/21-thumb.jpg" width="60" />
                    <span>20-21</span>
                </li>
                <li class="d">
                    <img class="page-22" height="60" src="../media/catalogue/22-thumb.jpg" width="60" />
                    <img class="page-23" height="60" src="../media/catalogue/23-thumb.jpg" width="60" />
                    <span>22-23</span>
                </li>
                <li class="d">
                    <img class="page-24" height="60" src="../media/catalogue/24-thumb.jpg" width="60" />
                    <img class="page-25" height="60" src="../media/catalogue/25-thumb.jpg" width="60" />
                    <span>24-25</span>
                </li>
                <li class="d">
                    <img class="page-26" height="60" src="../media/catalogue/26-thumb.jpg" width="60" />
                    <img class="page-27" height="60" src="../media/catalogue/27-thumb.jpg" width="60" />
                    <span>26-27</span>
                </li>
                <li class="d">
                    <img class="page-28" height="60" src="../media/catalogue/28-thumb.jpg" width="60" />
                    <img class="page-29" height="60" src="../media/catalogue/29-thumb.jpg" width="60" />
                    <span>28-29</span>
                </li>
                <li class="d">
                    <img class="page-30" height="60" src="../media/catalogue/30-thumb.jpg" width="60" />
                    <img class="page-31" height="60" src="../media/catalogue/31-thumb.jpg" width="60" />
                    <span>30-31</span>
                </li>
                <li class="d">
                    <img class="page-32" height="60" src="../media/catalogue/32-thumb.jpg" width="60" />
                    <img class="page-33" height="60" src="../media/catalogue/33-thumb.jpg" width="60" />
                    <span>32-33</span>
                </li>
                <li class="d">
                    <img class="page-34" height="60" src="../media/catalogue/34-thumb.jpg" width="60" />
                    <img class="page-35" height="60" src="../media/catalogue/35-thumb.jpg" width="60" />
                    <span>34-35</span>
                </li>
                <li class="d">
                    <img class="page-36" height="60" src="../media/catalogue/36-thumb.jpg" width="60" />
                    <img class="page-37" height="60" src="../media/catalogue/37-thumb.jpg" width="60" />
                    <span>36-37</span>
                </li>
                <li class="d">
                    <img class="page-38" height="60" src="../media/catalogue/38-thumb.jpg" width="60" />
                    <img class="page-39" height="60" src="../media/catalogue/39-thumb.jpg" width="60" />
                    <span>38-39</span>
                </li>
                <li class="d">
                    <img class="page-40" height="60" src="../media/catalogue/40-thumb.jpg" width="60" />
                    <img class="page-41" height="60" src="../media/catalogue/41-thumb.jpg" width="60" />
                    <span>40-41</span>
                </li>
                <li class="d">
                    <img class="page-42" height="60" src="../media/catalogue/42-thumb.jpg" width="60" />
                    <img class="page-43" height="60" src="../media/catalogue/43-thumb.jpg" width="60" />
                    <span>42-43</span>
                </li>
                <li class="d">
                    <img class="page-44" height="60" src="../media/catalogue/44-thumb.jpg" width="60" />
                    <img class="page-45" height="60" src="../media/catalogue/45-thumb.jpg" width="60" />
                    <span>44-45</span>
                </li>
                <li class="d">
                    <img class="page-46" height="60" src="../media/catalogue/46-thumb.jpg" width="60" />
                    <img class="page-47" height="60" src="../media/catalogue/47-thumb.jpg" width="60" />
                    <span>46-47</span>
                </li>
                <li class="d">
                    <img class="page-48" height="60" src="../media/catalogue/48-thumb.jpg" width="60" />
                    <img class="page-49" height="60" src="../media/catalogue/49-thumb.jpg" width="60" />
                    <span>48-49</span>
                </li>
                <li class="d">
                    <img class="page-50" height="60" src="../media/catalogue/50-thumb.jpg" width="60" />
                    <img class="page-51" height="60" src="../media/catalogue/51-thumb.jpg" width="60" />
                    <span>50-51</span>
                </li>
                <li class="d">
                    <img class="page-52" height="60" src="../media/catalogue/52-thumb.jpg" width="60" />
                    <img class="page-53" height="60" src="../media/catalogue/53-thumb.jpg" width="60" />
                    <span>52-53</span>
                </li>
                <li class="d">
                    <img class="page-54" height="60" src="../media/catalogue/54-thumb.jpg" width="60" />
                    <img class="page-55" height="60" src="../media/catalogue/55-thumb.jpg" width="60" />
                    <span>54-55</span>
                </li>
                <li class="d">
                    <img class="page-56" height="60" src="../media/catalogue/56-thumb.jpg" width="60" />
                    <img class="page-57" height="60" src="../media/catalogue/57-thumb.jpg" width="60" />
                    <span>56-57</span>
                </li>
                <li class="d">
                    <img class="page-58" height="60" src="../media/catalogue/58-thumb.jpg" width="60" />
                    <img class="page-59" height="60" src="../media/catalogue/59-thumb.jpg" width="60" />
                    <span>58-59</span>
                </li>
                <li class="d">
                    <img class="page-60" height="60" src="../media/catalogue/60-thumb.jpg" width="60" />
                    <img class="page-61" height="60" src="../media/catalogue/61-thumb.jpg" width="60" />
                    <span>60-61</span>
                </li>
                <li class="d">
                    <img class="page-62" height="60" src="../media/catalogue/62-thumb.jpg" width="60" />
                    <img class="page-63" height="60" src="../media/catalogue/63-thumb.jpg" width="60" />
                    <span>62-63</span>
                </li>
                <li class="i">
                    <img class="page-64" height="60" src="../media/catalogue/64-thumb.jpg" width="60" />
                    <span>64</span>
                </li>
            </ul>
        </div>
    </div>
</div>

<script type="text/javascript">
    function loadApp() {
        $j('#canvas').fadeIn(1000);
        var flipbook = $j('.magazine');

        // Check if the CSS was already loaded
        if (flipbook.width()==0 || flipbook.height()==0) {
            setTimeout(loadApp, 10);
            return;
        }

        // Create the flipbook
        flipbook.turn({
            // Magazine width
            width: 1200,
            // Magazine height
            height: 600,
            // Duration in millisecond
            duration: 1000,
            // Hardware acceleration
            acceleration: !isChrome(),
            // Enables gradients
            gradients: true,
            // Auto center this flipbook
            autoCenter: true,
            // Elevation from the edge of the flipbook when turning a page
            elevation: 50,
            // The number of pages
            pages: 64,
            // Events
            when: {
                turning: function(event, page, view) {
                    var book = $j(this),
                        currentPage = book.turn('page'),
                        pages = book.turn('pages');
                    // Update the current URI
                    jshash.go('page/' + page).update();
                    // Show and hide navigation buttons
                    disableControls(page);
                    $j('.thumbnails .page-'+currentPage).
                    parent().
                    removeClass('current');
                    $j('.thumbnails .page-'+page).
                    parent().
                    addClass('current');
                },
                turned: function(event, page, view) {
                    disableControls(page);
                    $j(this).turn('center');
                    if (page==1) {
                        $j(this).turn('peel', 'br');
                    }
                },

                missing: function (event, pages) {
                    // Add pages that aren't in the magazine
                    for (var i = 0; i < pages.length; i++)
                        addPage(pages[i], $j(this));
                }
            }
        });

        // Zoom.js
        $j('.magazine-viewport').zoom({
            flipbook: $j('.magazine'),
            max: function() {
                return largeMagazineWidth()/$j('.magazine').width();
            },
            when: {
                swipeLeft: function() {
                    $j(this).zoom('flipbook').turn('next');
                },
                swipeRight: function() {
                    $j(this).zoom('flipbook').turn('previous');
                },
                resize: function(event, scale, page, pageElement) {
                    if (scale==1)
                        loadSmallPage(page, pageElement);
                    else
                        loadLargePage(page, pageElement);
                },
                zoomIn: function () {
                    $j('.thumbnails').hide();
                    $j('.made').hide();
                    $j('.magazine').removeClass('animated').addClass('zoom-in');
                    $j('.zoom-icon').removeClass('zoom-icon-in').addClass('zoom-icon-out');

                    if (!window.escTip && !$j.isTouch) {
                        escTip = true;
                        $j('<div />', {'class': 'exit-message'}).
                        html('<div>Press ESC to exit</div>').
                        appendTo($j('body')).
                        delay(2000).
                        animate({opacity:0}, 500, function() {
                            $j(this).remove();
                        });
                    }
                },
                zoomOut: function () {
                    $j('.exit-message').hide();
                    $j('.thumbnails').fadeIn();
                    $j('.made').fadeIn();
                    $j('.zoom-icon').removeClass('zoom-icon-out').addClass('zoom-icon-in');
                    setTimeout(function(){
                        $j('.magazine').addClass('animated').removeClass('zoom-in');
                        resizeViewport();
                    }, 0);
                }
            }
        });

        // Zoom event
        if ($j.isTouch)
            $j('.magazine-viewport').bind('zoom.doubleTap', zoomTo);
        else
            $j('.magazine-viewport').bind('zoom.tap', zoomTo);

        // Using arrow keys to turn the page
        $j(document).keydown(function(e) {
            var previous = 37, next = 39, esc = 27;
            switch (e.keyCode) {
                case previous:
                    // left arrow
                    $j('.magazine').turn('previous');
                    e.preventDefault();
                    break;
                case next:
                    //right arrow
                    $j('.magazine').turn('next');
                    e.preventDefault();
                    break;
                case esc:
                    $j('.magazine-viewport').zoom('zoomOut');
                    e.preventDefault();
                    break;
            }
        });

        // URIs - Format #/page/1
        jshash.on('^page\/([0-9]*)$', {
            yep: function(path, parts) {
                var page = parts[1];
                if (page!==undefined) {
                    if ($j('.magazine').turn('is'))
                        $j('.magazine').turn('page', page);
                }
            },
            nop: function(path) {
                if ($j('.magazine').turn('is'))
                    $j('.magazine').turn('page', 1);
            }
        });

        $j(window).resize(function() {
            resizeViewport();
        }).bind('orientationchange', function() {
            resizeViewport();
        });

        // Events for thumbnails
        $j('.thumbnails').click(function(event) {
            var page;
            if (event.target && (page=/page-([0-9]+)/.exec($j(event.target).attr('class'))) ) {
                $j('.magazine').turn('page', page[1]);
            }
        });

        $j('.thumbnails li')
            .bind($j.mouseEvents.over, function() {
                $j(this).addClass('thumb-hover');
            })
            .bind($j.mouseEvents.out, function() {
                $j(this).removeClass('thumb-hover');
            });

        if ($j.isTouch) {
            $j('.thumbnails').
            addClass('thumbanils-touch').
            bind($j.mouseEvents.move, function(event) {
                event.preventDefault();
            });
        } else {
            $j('.thumbnails ul').mouseover(function() {
                $j('.thumbnails').addClass('thumbnails-hover');
            }).mousedown(function() {
                return false;
            }).mouseout(function() {
                $j('.thumbnails').removeClass('thumbnails-hover');
            });
        }

        // Regions
        if ($j.isTouch) {
            $j('.magazine').bind('touchstart', regionClick);
        } else {
            $j('.magazine').click(regionClick);
        }

        // Events for the next button
        $j('.next-button').bind($j.mouseEvents.over, function() {
            $j(this).addClass('next-button-hover');
        }).bind($j.mouseEvents.out, function() {
            $j(this).removeClass('next-button-hover');
        }).bind($j.mouseEvents.down, function() {
            $j(this).addClass('next-button-down');
        }).bind($j.mouseEvents.up, function() {
            $j(this).removeClass('next-button-down');
        }).click(function() {
            $j('.magazine').turn('next');
        });

        // Events for the next button
        $j('.previous-button').bind($j.mouseEvents.over, function() {
            $j(this).addClass('previous-button-hover');
        }).bind($j.mouseEvents.out, function() {
            $j(this).removeClass('previous-button-hover');
        }).bind($j.mouseEvents.down, function() {
            $j(this).addClass('previous-button-down');
        }).bind($j.mouseEvents.up, function() {
            $j(this).removeClass('previous-button-down');
        }).click(function() {
            $j('.magazine').turn('previous');
        });

        resizeViewport();
        $j('.magazine').addClass('animated');
    }

    // Zoom icon
    $j('.zoom-icon').bind('mouseover', function() {
        if ($j(this).hasClass('zoom-icon-in'))
            $j(this).addClass('zoom-icon-in-hover');

        if ($j(this).hasClass('zoom-icon-out'))
            $j(this).addClass('zoom-icon-out-hover');
    }).bind('mouseout', function() {
        if ($j(this).hasClass('zoom-icon-in'))
            $j(this).removeClass('zoom-icon-in-hover');

        if ($j(this).hasClass('zoom-icon-out'))
            $j(this).removeClass('zoom-icon-out-hover');
    }).bind('click', function() {
        if ($j(this).hasClass('zoom-icon-in'))
            $j('.magazine-viewport').zoom('zoomIn');
        else if ($j(this).hasClass('zoom-icon-out'))
            $j('.magazine-viewport').zoom('zoomOut');
    });
    $j('#canvas').hide();

    // Load the HTML4 version if there's not CSS transform
    yepnope({
        test : Modernizr.csstransforms,
        yep: ['../js/catalogue/lib/turn.js'],
        nope: ['../js/catalogue/lib/turn.html4.js'],
        both: ['../js/catalogue/lib/zoom.js', '../js/catalogue/magazine/js/magazine.js', '../js/catalogue/magazine/css/magazine.css'],
        complete: loadApp
    });
</script>
