<?php
/**
 * @copyright Copyright (c) 2014 Sergey Cherepanov (sergey@cherepanov.org.ua)
 * @license Creative Commons Attribution 3.0 License
 */

/** @var Open_Gallery_Block_Scripts $this */
?>
<script>var requireJsBaseUrl = '<?php echo $this->getRequireDirUrl()?>';</script>
<script src="http://jwpsrv.com/library/Sp6Xhh53EeSiiSIACtqXBA.js"></script>
<script data-main="<?php echo $this->getBootstrapUrl();?>" src="<?php echo $this->getRequireUrl(); ?>"></script>
