<?php
/**
 * Magiccart 
 * @category    Magiccart 
 * @copyright   Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: Magiccart<team.magiccart@gmail.com>
 * @@Create Date: 2014-06-07 12:27:23
 * @@Modify Date: 2015-04-22 14:40:13
 * @@Function:
 */ 
?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php $_items = $this->getRecentItems(); ?>
<div class="mini-maincart">
	<div class="mini-contentCart">
		<?php if(count($_items)): ?>
        <div class="block-content">
            <!-- <p class="block-subtitle"><?php //echo $this->__('Recently added item(s)') ?></p> -->
            <ol id="cart-sidebar" class="mini-products-list clearfix">
                <?php foreach($_items as $_item): ?>
<!--                    alobencher/default/template/checkout/cart/sidebar/default.phtml-->
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach; ?>
            </ol>
            <p class="subtotal">
                <?php if ($this->canApplyMsrp()): ?>
                    <span class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                <?php else: ?>
                    <span class="label"><?php echo $this->__('Total:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                    <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                        <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                    <?php endif; ?>
                <?php endif; ?>
            </p>
        </div>

		<?php else: ?>
		<div class="block-content">
			<p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
		</div>
		<?php endif ?>	
	</div>
</div>

