<?php
/**
 * @copyright Copyright (c) 2014 Sergey Cherepanov (sergey@cherepanov.org.ua)
 * @license Creative Commons Attribution 3.0 License
 */

/** @var Open_Gallery_Block_Item_List $this */
/** @var Open_Gallery_Model_Category $item */
$item           = $this->getCategory();
/** @var Open_Gallery_Model_Resource_Item_Collection $itemCollection */
$itemCollection = $this->getItemCollection();
$helper         = Mage::helper('open_gallery');
$imageWidth     = $helper->getListImageWidth();
$imageHeight    = $helper->getListImageHeight();
$columnCount    = $this->hasData('column_count') ? $this->getData('column_count') : 4;
?>



<h1><?php echo $item->getTitle();?></h1>

<ul class="gallery-list gallery-item-list">
    <?php $i = 0; foreach ($itemCollection as $item):
        /** @var Open_Gallery_Model_Item $item */ ?>
    <?php if($i && 0 == $i%$columnCount):?>
    </ul>
<ul class="gallery-list gallery-item-list">
    <?php endif;?>
        <li class="gallery-item">
            <a href="<?php echo $this->getItemBoxUrl($item);?>" class="gallery-image gallery-box">
                <img width="<?php echo $imageWidth;?>" height="<?php echo $imageHeight;?>" src="<?php echo $this->getThumbnailUrl($item)?>" alt="<?php echo $item->getTitle();?>" />
            </a>
            <a class="gallery-title" href="<?php echo $this->getItemUrl($item);?>">
                <span><?php echo $item->getTitle();?></span>
            </a>
        </li>
    <?php $i++; endforeach;?>
</ul>
