<?php 
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event list template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php 
$_events = $this->getEvents();
$imgWidth = 205;
$imgHeight = 205;
?>
<div class="page-title event-title">
    <?php if (Mage::helper('istans_nailgallery/event')->isRssEnabled()) : ?>
        <a href="<?php echo Mage::helper('istans_nailgallery/event')->getRssUrl();?>" class="link-rss"><?php echo Mage::helper('istans_nailgallery')->__('Subscribe to RSS Feed')?></a>
    <?php endif;?>
    <h1><?php echo Mage::helper('istans_nailgallery')->__('Event') ?></h1>
</div>
<?php if ($_events->getSize() > 0) :?>
    <?php //echo $this->getPagerHtml(); ?>
    <ul class="products-grid first last odd">
    <?php foreach ($_events as $_event) : ?>
        <li class="col3 item">
            <div class="item-inner">
            <a href="<?php echo $_event->getEventUrl()?>">
                <div class="product-image">
                <?php $img_orig = 'event/file'. $_event->getImage(); ?>
                <?php $img = Mage::helper('istans_nailgallery')->resizeImg($img_orig, $imgWidth, $imgHeight); ?>
                    <img src="<?php echo $img;?>" alt="" />
                </div>
                <div class="price-review">
                    <?php echo $_event->getCaption();?>
                </div>
            </a>
            </div>    
        </li>
    <?php endforeach;?>
    </ul>
    <?php echo $this->getPagerHtml(); ?>
<?php else : ?>
    <?php echo Mage::helper('istans_nailgallery')->__('There are no event at this moment');?>
<?php endif;?>
