<?php 
/**
 * Istans_Nailgallery extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category       Istans
 * @package        Istans_Nailgallery
 * @copyright      Copyright (c) 2016
 * @license        http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Event Event image list template
 *
 * @category    Istans
 * @package     Istans_Nailgallery
 * @author      Ultimate Module Creator
 */
?>
<?php $_eventimages = $this->getEventimages(); ?>
<?php if ($_eventimages->getSize() > 0) :?>
<div class="eventimage-title">
    <h2><?php echo Mage::helper('istans_nailgallery')->__('Event images') ?></h2>
</div>
    <ul class="products-grid first last odd">
    <?php foreach ($_eventimages as $_eventimage) : ?>
        <li class="col3 item">
            <div class="item-inner">
                <div class="product-image">
                <?php $img_orig = '/eventimage/image'. $_eventimage->getFile(); ?>
                <?php $img = Mage::helper('istans_nailgallery')->resizeImg($img_orig, $imgWidth, $imgHeight); ?>
                <a class="fancybox-thumb" rel="fancybox-thumb" href="<?php echo '/media'.$img_orig;?>" title="<?php echo $_eventimage->getTitle();?>">
                    <img src="<?php echo $img;?>" alt="" />
                </a>                
                </div>
                <div class="price-review">
                    <?php echo $_eventimage->getTitle();?>
                </div>
            </div>    
        </li>
    <?php endforeach;?>
    </ul>
<?php endif;?>

<script type="text/javascript">
    jQuery(document).ready(function() {
	jQuery(".fancybox-thumb").fancybox({
		prevEffect	: 'none',
		nextEffect	: 'none',
		helpers	: {
			title	: {
				type: 'outside'
			},
			thumbs	: {
				width	: 205,
				height	: 205
			}
		}
	});
});
</script>